version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-nexora}
      POSTGRES_USER: ${DB_USERNAME:-nexora}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-nexora}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      DB_URL: ${DB_URL:-jdbc:postgresql://db:5432/nexora}
      DB_USERNAME: ${DB_USERNAME:-nexora}
      DB_PASSWORD: ${DB_PASSWORD:-nexora}
      FRONTEND_URL: ${FRONTEND_URL:-http://16.16.201.70:5173}
      CORS_PRODUCTION_ORIGIN: ${CORS_PRODUCTION_ORIGIN:-http://16.16.201.70:5173}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:5173,http://127.0.0.1:5173,http://0.0.0.0:5173,http://16.16.201.70:5173}
      JWT_SECRET: 9a6230f6534571ef99c92284910cfb19d45e4544d67390cf2c40c83a0058bbf43dcf49b38466b0d91244d28d08c5c7d0d0c3eb1492b45cf5dc128b9d3b4502d68e2197f26d36
      MAIL_USERNAME: nexora.entertainment18@gmail.com
      MAIL_PASSWORD: jjvluwlcokqeahjm
      VITE_TMDB_BEARER_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwMDcyYzA3YWZhMDBjMWU2NjMyMGQ3MThjYWNlYTRiZCIsIm5iZiI6MTc4MjY2MDI0MC42OTcsInN1YiI6IjZhNDEzYzkwYmNkZTgzNmFkMTQ1ZjBlNyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.AOABVmAFn-XWGu4cvb-MbfqkW2XnQRl60WsuT1nHZLw
      VITE_OMDB_API_KEY: a6e32f97
      S3_BUCKET: ${S3_BUCKET:-}
      AWS_REGION: ${AWS_REGION:-eu-north-1}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME:-Nexora}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY:-797675238841127}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET:-GdtF0g-sFne4MuhSffXtp4coNHo}
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_TARGET: http://backend:8081
        VITE_TMDB_BEARER_TOKEN: ${VITE_TMDB_BEARER_TOKEN:-eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwMDcyYzA3YWZhMDBjMWU2NjMyMGQ3MThjYWNlYTRiZCIsIm5iZiI6MTc4MjY2MDI0MC42OTcsInN1YiI6IjZhNDEzYzkwYmNkZTgzNmFkMTQ1ZjBlNyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.AOABVmAFn-XWGu4cvb-MbfqkW2XnQRl60WsuT1nHZLw}
        VITE_OMDB_API_KEY: ${VITE_OMDB_API_KEY:-a6e32f97}
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      VITE_API_TARGET: http://backend:8081
      VITE_TMDB_BEARER_TOKEN: ${VITE_TMDB_BEARER_TOKEN:-eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwMDcyYzA3YWZhMDBjMWU2NjMyMGQ3MThjYWNlYTRiZCIsIm5iZiI6MTc4MjY2MDI0MC42OTcsInN1YiI6IjZhNDEzYzkwYmNkZTgzNmFkMTQ1ZjBlNyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.AOABVmAFn-XWGu4cvb-MbfqkW2XnQRl60WsuT1nHZLw}
      VITE_OMDB_API_KEY: ${VITE_OMDB_API_KEY:-a6e32f97}
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
